import os
import re

# Directory paths
BASE_DIR = r"c:\Users\Lenovo\Desktop\逼哥机场"
ARTICLES_DIR = os.path.join(BASE_DIR, "articles")

# 7 Airports metadata
airports_data = [
    {
        "id": "liyun",
        "name": "鲤云",
        "site": "鲤云.com",
        "url": "https://鲤云.com",
        "logo": "images/liyun_logo.png",
        "rank": "TOP 8",
        "rank_num": 8,
        "badge_tag": "TOP 8 评测",
        "price_start": "¥5",
        "tags": ["Shadowsocks / Trojan", "IEPL 专线中转", "超低门槛高性价比"],
        "metrics": {"ping": "21ms", "speed": "720+", "uptime": "99.4%"},
        "subtext": "🐟 超低门槛入局，全专线中转加速",
        "packages": [
            ("5元", "100GB", "小鲤"),
            ("8元", "200GB", "中鲤"),
            ("15元", "400GB", "大鲤"),
            ("59元", "不限时200G", "不限时"),
            ("96元", "特惠年付256G", "特惠年付"),
            ("16元", "特惠季付128G", "特惠季付"),
        ],
        "card_tags": "budget stream",
        "desc": "鲤云以极致的入门性价比与稳定中转线路为核心特色，提供低至 5 元/月的套餐方案。全站节点采用高效中转优化，晚高峰流媒体 4K 播放无压力，非常适合学生党与入门用户。"
    },
    {
        "id": "shanshuiyun",
        "name": "山水云",
        "site": "山水云.com",
        "url": "https://山水云.com",
        "logo": "images/shanshuiyun_logo.png",
        "rank": "TOP 9",
        "rank_num": 9,
        "badge_tag": "TOP 9 评测",
        "price_start": "¥12",
        "tags": ["VLESS / Trojan", "BGP 优质中转", "国风主题高稳定性"],
        "metrics": {"ping": "24ms", "speed": "780+", "uptime": "99.5%"},
        "subtext": "⛰️ 山水有相逢，高稳 BGP 多线中继",
        "packages": [
            ("12元", "100G", "琴"),
            ("20元", "200G", "棋"),
            ("39元", "500G", "书"),
            ("99元", "不限时100G", "不限时"),
            ("36元", "季付128G轻量套餐", "季付轻量"),
            ("129元", "年付128G轻量套餐", "年付轻量"),
            ("88元", "年付64G轻量套餐", "年付轻量"),
        ],
        "card_tags": "budget stream",
        "desc": "山水云采用琴棋书画国风主题命名套餐，全线路接入 BGP 多线入口中转，兼顾高连通率与抗封锁能力。套餐类型丰富，涵盖轻量季付/年付及不限时包，极具灵活度。"
    },
    {
        "id": "miaomiaoyun",
        "name": "秒秒云",
        "site": "秒秒云.com",
        "url": "https://秒秒云.com",
        "logo": "images/miaomiaoyun_logo.png",
        "rank": "TOP 10",
        "rank_num": 10,
        "badge_tag": "TOP 10 评测",
        "price_start": "¥9",
        "tags": ["Hysteria 2 / V2Ray", "极速秒开体验", "全能流媒体解锁"],
        "metrics": {"ping": "19ms", "speed": "850+", "uptime": "99.6%"},
        "subtext": "⚡ 网页秒开，晚高峰万兆带宽保障",
        "packages": [
            ("9元", "128G", "探花"),
            ("15元", "256G", "榜眼"),
            ("29元", "512G", "状元"),
            ("59元", "不限时100G", "不限时"),
            ("18元", "64G季付特惠", "季付特惠"),
            ("88元", "100G年付特惠", "年付特惠"),
        ],
        "card_tags": "iepl stream",
        "desc": "秒秒云主打高吞吐量与极速响应速度，率先全面部署 Hysteria 2 新协议与 IPLC 专线通道。探花、榜眼、状元科举名次阶梯套餐性价比极佳，8K 视频拖拽零缓冲。"
    },
    {
        "id": "jinyun",
        "name": "锦云",
        "site": "锦云111.com",
        "url": "https://锦云111.com",
        "logo": "images/jinyun_logo.png",
        "rank": "TOP 11",
        "rank_num": 11,
        "badge_tag": "TOP 11 评测",
        "price_start": "¥6",
        "tags": ["Trojan / Shadowsocks", "办公娱乐全场景", "低延迟住宅 IP"],
        "metrics": {"ping": "23ms", "speed": "760+", "uptime": "99.3%"},
        "subtext": "☁️ 前程似锦，稳定高效的跨境连接",
        "packages": [
            ("6元", "50G", "体验版"),
            ("9元", "100G", "日常版"),
            ("16元", "200G", "办公版"),
            ("99元", "不限时100G", "不限时"),
            ("99元", "128G年付特惠", "年付特惠"),
            ("18元", "64G季付特惠", "季付特惠"),
        ],
        "card_tags": "budget stream",
        "desc": "锦云主打轻量日常与高效办公场景，提供了 6 元起步的极低体验门槛。线路针对 ChatGPT/Claude 等 AI 工具以及 TikTok 进行了专门优化，原生 IP 干净度极高。"
    },
    {
        "id": "xiongmaocloud",
        "name": "熊猫cloud",
        "site": "熊猫导航.com",
        "url": "https://熊猫导航.com",
        "logo": "images/xiongmaocloud_logo.png",
        "rank": "TOP 12",
        "rank_num": 12,
        "badge_tag": "TOP 12 评测",
        "price_start": "¥6",
        "tags": ["Vmess / Trojan", "超大流量包", "萌宠品质保驾护航"],
        "metrics": {"ping": "26ms", "speed": "800+", "uptime": "99.4%"},
        "subtext": "🐼 国宝级品质，海量大流量首选",
        "packages": [
            ("6元", "300G", "基础版"),
            ("10元", "600G", "进阶版"),
            ("15元", "1200G", "豪华版"),
            ("66元", "不限时600G", "不限时"),
            ("24元", "季付500G特惠", "季付特惠"),
        ],
        "card_tags": "budget stream",
        "desc": "熊猫cloud以超大流量池与极低单 G 单价火爆圈内，6 元即送 300GB 流量，15 元更有 1200GB 狂暴大包！无论是追剧大户还是下载达人都能彻底告别流量焦虑。"
    },
    {
        "id": "jiuyun",
        "name": "九云",
        "site": "九云.com",
        "url": "https://九云.com",
        "logo": "images/jiuyun_logo.png",
        "rank": "TOP 13",
        "rank_num": 13,
        "badge_tag": "TOP 13 评测",
        "price_start": "¥6",
        "tags": ["Shadowsocks / IPLC", "聚财吉祥主题", "多端并发保障"],
        "metrics": {"ping": "20ms", "speed": "820+", "uptime": "99.5%"},
        "subtext": "🐉 九霄云外，财源滚滚高稳专线",
        "packages": [
            ("6元", "150G", "招财版"),
            ("9元", "300G", "聚财版"),
            ("16元", "600G", "旺财版"),
            ("99元", "300G一次性", "鸿运版"),
            ("99元一年", "特惠年付400G", "年付特惠"),
            ("18元一季度", "特惠季付200G", "季付特惠"),
        ],
        "card_tags": "iepl stream",
        "desc": "九云采用招财、聚财、旺财、鸿运等喜庆吉祥名称命名套餐，底层接入优质 IPLC 跨境专线，全节点 1 倍率不扣费。线路抗封锁能力强，兼顾稳定与高速。"
    },
    {
        "id": "baoyun",
        "name": "宝云",
        "site": "宝云.com",
        "url": "https://宝云.com",
        "logo": "images/baoyun_logo.png",
        "rank": "TOP 14",
        "rank_num": 14,
        "badge_tag": "TOP 14 评测",
        "price_start": "¥4",
        "tags": ["VLESS / Trojan", "拒绝月租刺客", "传家宝不限时包"],
        "metrics": {"ping": "25ms", "speed": "750+", "uptime": "99.3%"},
        "subtext": "💎 招财进宝，极致高性价比中转",
        "packages": [
            ("4元", "200G", "福宝"),
            ("8元", "500G", "财宝"),
            ("13元", "1000G", "金宝"),
            ("29元", "100G一次性", "传家宝"),
            ("39元", "500G一次性", "传世宝"),
            ("59元", "1000G一次性", "传承宝"),
            ("19元", "季付500G特惠", "季付特惠"),
        ],
        "card_tags": "budget stream",
        "desc": "宝云拥有全网最亲民的 4 元 200G 福宝套餐，并拥有传家宝、传世宝、传承宝等多元化一次性不限时流量包，是学生党、轻度用户与备用节点的不二之选。"
    }
]

print("Script template ready!")
